dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- export TZ=Brazil/East
- cd backend
deploy:
    provider: heroku
    api_key:
        - secure: $SECURE_KEY
    run: "git subtree push --prefix backend heroku master"
