version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:9.6
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts      
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./frontend/build:/usr/share/nginx/html/
      # Configuração do proxy reverso
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    environment:
      REACT_APP_API_BASE_URL: http://localhost/api/
    depends_on:
      - app
  app:
    build: ./backend/
    depends_on:
      - db